// <auto-generated />
namespace MaharajaRestaurant.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class migration14 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration14));
        
        string IMigrationMetadata.Id
        {
            get { return "201412081102355_migration14"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
